// Generated by CoffeeScript 1.3.3
(function() {
  var facebook;

  facebook = require('../lib/facebook');

  exports.index = function(req, res) {
    var token;
    token = req.cookies.token;
    return facebook.get_friend(token, function(friend) {
      return res.send(friend);
    });
  };

}).call(this);
