// Generated by CoffeeScript 1.3.3
(function() {
  var auth;

  auth = require('../lib/authentication');

  exports.index = function(req, res) {
    var signed_request, token;
    signed_request = req.param('signed_request');
    if (signed_request) {
      token = auth.getToken(signed_request);
      res.cookie('token', token);
      return res.render('index');
    } else {
      return res.render('index');
    }
  };

}).call(this);
