// Generated by CoffeeScript 1.3.3
(function() {
  var missions;

  missions = require('../lib/missions');

  exports["new"] = function(req, res) {
    var token;
    token = req.cookies.token;
    return missions.create(token, function(mission) {
      return res.send(mission);
    });
  };

}).call(this);
