// Generated by CoffeeScript 1.3.3
(function() {
  var clue, creator, facebook;

  facebook = require('../lib/facebook');

  clue = require('../lib/clue');

  creator = require('../lib/creator');

  exports.index = function(req, res) {
    var friend, missions, new_mission, token;
    friend = '';
    missions = '';
    token = req.cookies.token;
    facebook.getFriend(token, function(friend) {
      return clue.addClues(friend, function(friend) {
        return friend = friend;
      });
    });
    db.getMissions(function(missions) {
      return missions = missions;
    });
    new_mission = creator.createMission({
      levels: 3,
      clues: friend.clues,
      missions: missions
    });
    db.saveMission(new_mission, function() {
      return console.log('mission saved');
    });
    return new_mission;
  };

}).call(this);
