// Generated by CoffeeScript 1.3.3
(function() {
  var base64url;

  base64url = require('b64url');

  exports.parse_signed_request = function(signed_request) {
    var data, encoded_data, json;
    encoded_data = signed_request.split('.', 2);
    json = base64url.decode(encoded_data[1]);
    data = JSON.parse(json);
    return data.oauth_token;
  };

}).call(this);
