// Generated by CoffeeScript 1.3.3
(function() {
  var base64url, parse_signed_request;

  base64url = require('b64url');

  parse_signed_request = function(signed_request) {
    var data, encoded_data, json;
    encoded_data = signed_request.split('.', 2);
    json = base64url.decode(encoded_data[1]);
    return data = JSON.parse(json);
  };

}).call(this);
