// Generated by CoffeeScript 1.3.3
(function() {
  var get_friend_info, get_random_friend, https, querystring;

  https = require('https');

  querystring = require('querystring');

  get_random_friend = function(token, callback) {
    var buffer, options, parseResult, req;
    buffer = '';
    parseResult = function() {
      var json;
      json = JSON.parse(buffer);
      return callback(json.data);
    };
    options = {
      host: 'graph.facebook.com',
      path: "/fql?q=SELECT+uid,+name+FROM+user+WHERE+uid+IN+(SELECT+uid2+FROM+friend+WHERE+uid1+=+me())+ORDER+BY+rand()+limit+1&access_token=" + token
    };
    req = https.get(options, function(res) {
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return buffer += chunk.toString();
      });
      return res.on('end', parseResult);
    });
    return req.on('error', function(e) {
      return console.log(e);
    });
  };

  get_friend_info = function(uid, token, callback) {
    var batch_request, buffer, options, params, parseResult, req;
    buffer = '';
    parseResult = function() {
      var friend, json, likes;
      json = JSON.parse(buffer);
      friend = JSON.parse(json[0].body);
      likes = JSON.parse(json[1].body);
      friend.likes = likes.data;
      return callback(friend);
    };
    params = {
      access_token: token,
      batch: "[ { 'method': 'GET', 'relative_url': '" + uid + "' }, { 'method': 'GET', 'relative_url': '" + uid + "/likes' } ]"
    };
    batch_request = querystring.stringify(params);
    options = {
      host: 'graph.facebook.com',
      path: "/",
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': batch_request.length
      }
    };
    req = https.request(options, function(res) {
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return buffer += chunk.toString();
      });
      return res.on('end', parseResult);
    });
    req.on('error', function(e) {
      return console.log(e);
    });
    req.write(batch_request);
    return req.end();
  };

  exports.get_friend = function(token, callback) {
    return get_random_friend(token, function(friend) {
      var uid;
      uid = friend[0].uid;
      return get_friend_info(uid, token, function(friend) {
        return callback(friend);
      });
    });
  };

}).call(this);
