// Generated by CoffeeScript 1.3.3
(function() {
  var clue, creator, facebook;

  facebook = require('../lib/facebook');

  clue = require('../lib/clue');

  creator = require('../lib/creator');

  exports.create = function(token, callback) {
    return facebook.getFriend(token, function(friend, suspects) {
      return clue.addClues(friend, function(friend) {
        return res.send({
          friend: friend,
          suspects: suspects
        });
      });
    });
  };

}).call(this);
