// Generated by CoffeeScript 1.3.3
(function() {
  var auth;

  auth = require('../lib/authentication');

  exports.index = function(req, res) {
    var signed_request;
    signed_request = req.param('signed_request');
    return auth.user(signed_request, function(err, user) {
      if (err) {
        return res.render('canvas', {
          url: auth.url
        });
      } else {
        req.session.id = user.id;
        req.session.token = user.token;
        return res.render('index');
      }
    });
  };

  exports.tester = function(req, res) {
    return res.render('index');
  };

}).call(this);
