// Generated by CoffeeScript 1.3.3
(function() {
  var quests;

  quests = require('../lib/quests');

  exports.create = function(req, res) {
    var id, token;
    id = req.session.id;
    token = req.session.token;
    return quests.create(id, token, function(quest) {
      return res.send([quest]);
    });
  };

}).call(this);
