// Generated by CoffeeScript 1.3.3
(function() {
  var getFriendInfo, getRandomFriends, graphAPI, https, qs;

  https = require('https');

  qs = require('querystring');

  graphAPI = function(path, callback) {
    var buffer, options, parseResult, req;
    buffer = '';
    parseResult = function() {
      var json;
      json = JSON.parse(buffer);
      return callback(json);
    };
    options = {
      host: 'graph.facebook.com',
      path: path
    };
    req = https.get(options, function(res) {
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return buffer += chunk.toString();
      });
      return res.on('end', parseResult);
    });
    return req.on('error', function(e) {
      return console.log(e);
    });
  };

  exports.getUser = function(token, callback) {
    var path;
    path = "/me?access_token=" + token;
    return graphAPI(path, function(json) {
      return callback(json.id, {
        name: json.name
      });
    });
  };

  getRandomFriends = function(token, callback) {
    var path;
    path = "/fql?q=SELECT+uid,+name+FROM+user+WHERE+uid+IN+(SELECT+uid2+FROM+friend+WHERE+uid1+=+me())+ORDER+BY+rand()+limit+3&access_token=" + token;
    return graphAPI(path, function(json) {
      return callback(json.data);
    });
  };

  getFriendInfo = function(uid, token, callback) {
    var batch_request, buffer, options, params, parseResult, req;
    buffer = '';
    parseResult = function() {
      var friend, json, likes;
      json = JSON.parse(buffer);
      friend = JSON.parse(json[0].body);
      likes = JSON.parse(json[1].body);
      friend.likes = likes.data;
      return callback(friend);
    };
    params = {
      access_token: token,
      batch: "[ { 'method': 'GET', 'relative_url': '" + uid + "' }, { 'method': 'GET', 'relative_url': '" + uid + "/likes' } ]"
    };
    batch_request = qs.stringify(params);
    options = {
      host: 'graph.facebook.com',
      path: "/",
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': batch_request.length
      }
    };
    req = https.request(options, function(res) {
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return buffer += chunk.toString();
      });
      return res.on('end', parseResult);
    });
    req.on('error', function(e) {
      return console.log(e);
    });
    req.write(batch_request);
    return req.end();
  };

  exports.getFriends = function(token, callback) {
    return getRandomFriends(token, function(friends) {
      var guilted;
      guilted = friends[0];
      return getFriendInfo(guilted.uid, token, function(guilted) {
        return callback(guilted, friends);
      });
    });
  };

}).call(this);
