// Generated by CoffeeScript 1.3.3
(function() {
  var async, clue, creator, db, facebook, organizeQuest;

  async = require('async');

  facebook = require('../lib/facebook');

  clue = require('../lib/clue');

  creator = require('../lib/creator');

  db = require('../lib/db');

  organizeQuest = function(path, suspects) {
    var quest;
    quest = path;
    quest.suspects = suspects;
    return quest;
  };

  exports.create = function(user_id, token, callback) {
    var quest_suspects;
    quest_suspects = [];
    return async.parallel({
      clues: function(callback) {
        return facebook.getFriend(token, function(friend, suspects) {
          quest_suspects = suspects;
          return clue.addClues(friend, function(clues) {
            return callback(null, clues);
          });
        });
      },
      missions: function(callback) {
        return db.getMissions(function(missions) {
          return callback(null, missions);
        });
      }
    }, function(err, results) {
      var path, quest;
      if (!err) {
        path = creator.createQuestPath({
          levels: 3,
          clues: results.clues,
          missions: results.missions
        });
        quest = organizeQuest(path, quest_suspects);
        return callback(quest);
      }
    });
  };

}).call(this);
