// Generated by CoffeeScript 1.3.3
(function() {
  var async, clue, creator, db, facebook;

  async = require('async');

  facebook = require('../lib/facebook');

  clue = require('../lib/clue');

  creator = require('../lib/creator');

  db = require('../lib/db');

  exports.create = function(user_id, token, callback) {
    return async.parallel({
      suspects: function(callback) {
        return facebook.getFriends(token, function(guilted, suspects) {
          return clue.addClues(guilted, function(clues) {
            suspects[0].clues = clues;
            return callback(null, suspects);
          });
        });
      },
      quest: function(callback) {
        return db.getMissions(function(missions) {
          var quest;
          quest = creator.createQuestPath({
            levels: 3,
            missions: missions
          });
          return callback(null, quest);
        });
      }
    }, function(err, results) {
      var quest;
      if (!err) {
        quest = results.quest;
        quest.suspects = results.suspects;
        return callback(quest);
      }
    });
  };

}).call(this);
